name: "build"

on:
  push:
    branches:
      - "dev"
      - "next"
  workflow_dispatch:

jobs:
  evaluate-os-configs:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        systems:
          - ringo
          - stargazer
          - youkai
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false
          planner: linux
          extra-conf: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            substituters = https://attic.karui.moe/karui https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
            trusted-public-keys = karui:8uidONyUZQeIiM7V0zmDXnSvMCLyZmwHvfJfAgFEbYc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE=

      - name: Evaluate Configuration
        run: nix eval ".#nixosConfigurations.${{ matrix.systems }}.config.system.build.toplevel"

  build-aarch64:
    runs-on: ubuntu-24.04-arm
    continue-on-error: true
    strategy:
      matrix:
        packages:
          - ddctoolbox
          - goldwarden
          - intel_fw
          - linux-asahi-fairydust
          - linux-asahi-fairydust.configfile
          - srb2kart-saturn
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo mkdir -p /etc/nix
          echo "machine attic.karui.moe password ${{ secrets.ATTIC_TOKEN }}" | sudo tee /etc/nix/netrc > /dev/null
      
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false
          planner: linux
          extra-conf: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            substituters = https://attic.karui.moe/karui https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
            trusted-public-keys = karui:8uidONyUZQeIiM7V0zmDXnSvMCLyZmwHvfJfAgFEbYc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE=

      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: nix build ".#${{ matrix.packages }}^*"
      - name: Push to cache
        run: |
          nix run github:zhaofengli/attic#default login karui https://attic.karui.moe ${{ secrets.ATTIC_TOKEN }}
          nix shell github:zhaofengli/attic#default --command ./scripts/push-all-outputs karui ${{ matrix.packages }}

  build-x86-64:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        packages:
          - srb2kart-saturn
          - goldwarden
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo mkdir -p /etc/nix
          echo "machine attic.karui.moe password ${{ secrets.ATTIC_TOKEN }}" | sudo tee /etc/nix/netrc > /dev/null
      
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false
          planner: linux
          extra-conf: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            substituters = https://attic.karui.moe/karui https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
            trusted-public-keys = karui:8uidONyUZQeIiM7V0zmDXnSvMCLyZmwHvfJfAgFEbYc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE=

      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: nix build ".#${{ matrix.packages }}^*"
      - name: Push to cache
        run: |
          nix run github:zhaofengli/attic#default login karui https://attic.karui.moe ${{ secrets.ATTIC_TOKEN }}
          nix shell github:zhaofengli/attic#default --command ./scripts/push-all-outputs karui ${{ matrix.packages }}
